# Install script for directory: F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/MinSizeRel/asymzoicpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/RelWithDebInfo/asymzoicpp.cp311-win_amd64.pyd")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/AboveGround/AsymmetricZOICPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/AboveGround/AsymmetricZOICPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/AboveGround/AsymmetricZOICPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/MinSizeRel/asymzoicpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/AboveGround/AsymmetricZOICPP/asymzoicpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/AboveGround/AsymmetricZOICPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/RelWithDebInfo/asymzoicpp.cp311-win_amd64.pyd")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/MinSizeRel/foncpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/RelWithDebInfo/foncpp.cp311-win_amd64.pyd")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FONCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FONCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FONCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/MinSizeRel/foncpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FONCPP/foncpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FONCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/RelWithDebInfo/foncpp.cp311-win_amd64.pyd")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/MinSizeRel/fixedsalcpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/RelWithDebInfo/fixedsalcpp.cp311-win_amd64.pyd")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FixedSalinityCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FixedSalinityCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FixedSalinityCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/MinSizeRel/fixedsalcpp.cp311-win_amd64.pyd")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
     "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FixedSalinityCPP/fixedsalcpp.cp311-win_amd64.pyd")
    if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
      message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
    endif()
    file(INSTALL DESTINATION "E:/miniconda_envs/pyMANGA_3.11_07.25/Lib/site-packages/ResourceLib/BelowGround/Individual/FixedSalinityCPP" TYPE MODULE FILES "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/RelWithDebInfo/fixedsalcpp.cp311-win_amd64.pyd")
  endif()
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
if(CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_COMPONENT MATCHES "^[a-zA-Z0-9_.+-]+$")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
  else()
    string(MD5 CMAKE_INST_COMP_HASH "${CMAKE_INSTALL_COMPONENT}")
    set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INST_COMP_HASH}.txt")
    unset(CMAKE_INST_COMP_HASH)
  endif()
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "F:/py_Workspace/pyMANGA_TEST_07.2025/22.07/pyMANGA/build-msvc/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
